const currencies = [
    { id: 1, name: '$' },
    { id: 2, name: '€' },
    { id: 3, name: 'ل.س' },
    { id: 4, name: 'ل.ت' }
];

const categories = [
  { id: 1, name: 'مركبات' },
  { id: 2, name: 'عقارات' },
  { id: 3, name: 'الكترونيات' },
  { id: 4, name: 'أثاث' },
  { id: 5, name: 'معدات صناعية' },
  { id: 6, name: 'ملابس' },
  { id: 7, name: 'المجتمع' },
  { id: 8, name: 'حيوانات' },
  { id: 9, name: 'فرص عمل' },
];

const subCategories = [
  { id: 1, name: 'سيارات سياحية', categoryId: 1 },
  { id: 2, name: 'سيارات كهربائية', categoryId: 1 },
  { id: 3, name: 'سيارات دفع رباعي', categoryId: 1 },
  { id: 4, name: 'سيارات بيك أب', categoryId: 1 },
  { id: 5, name: 'سيارات شحن', categoryId: 1 },
  { id: 6, name: 'ميكرو أو فان أو باصات', categoryId: 1 },
  { id: 7, name: 'اليات ثقيلة', categoryId: 1 },
  { id: 8, name: 'المركبات البحرية', categoryId: 1 },
  { id: 9, name: 'شقة', categoryId: 2 },
  { id: 10, name: 'اراضي', categoryId: 2 },
  { id: 11, name: 'محلات', categoryId: 2 },
  { id: 12, name: 'بناء كامل', categoryId: 2 },
  { id: 13, name: 'فيلا', categoryId: 2 },
  { id: 14, name: 'مزارع', categoryId: 2 },
  { id: 15, name: 'هواتف', categoryId: 3 },
  { id: 16, name: 'كمبيوتر ثابت', categoryId: 3 },
  { id: 17, name: 'لابتوب', categoryId: 3 },
  { id: 18, name: 'طائرات درون', categoryId: 3 },
  { id: 19, name: 'شاشات', categoryId: 3 },
  { id: 20, name: 'ألواح طاقة', categoryId: 3 },
  { id: 21, name: 'سيارات أطفال', categoryId: 4 },
  { id: 22, name: 'اكسسوارات', categoryId: 4 },
  { id: 23, name: 'غرف نوم', categoryId: 4 },
  { id: 24, name: 'غرف جلوس', categoryId: 4 },
  { id: 26, name: 'غرف ضيوف', categoryId: 4 },
  { id: 27, name: 'أثاث مكتب', categoryId: 4 },
  { id: 28, name: 'اكسسوارات و صمديات', categoryId: 4 },
  { id: 29, name: 'كهربائيات منزل', categoryId: 4 },
  { id: 30, name: 'أواني مطبخ', categoryId: 4 },
  { id: 31, name: 'أثاثات أخرى', categoryId: 4 },
  { id: 32, name: 'مطاعم و افران', categoryId: 5 },
  { id: 33, name: 'معامل بلاستيك و حديد', categoryId: 5 },
  { id: 34, name: 'معامل خياطة', categoryId: 5 },
  { id: 35, name: 'مولدات', categoryId: 5 },
  { id: 36, name: 'ديكورات محلات', categoryId: 5 },
  { id: 37, name: 'هنكارات', categoryId: 5 },
  { id: 38, name: 'معدات زراعية', categoryId: 5 },
  { id: 39, name: 'معدات أخرى', categoryId: 5 },
  { id: 40, name: 'ملابس رجالية', categoryId: 6 },
  { id: 41, name: 'ملابس نسائية', categoryId: 6 },
  { id: 42, name: 'ملابس أطفال', categoryId: 6 },
  { id: 43, name: 'ألعاب أطفال', categoryId: 6 },
  { id: 44, name: 'أدوات رياضية', categoryId: 6 },
  { id: 45, name: 'أدوات موسيقية', categoryId: 6 },
  { id: 46, name: 'كتب و مجلات', categoryId: 6 },
  { id: 47, name: 'أدوات منزلية', categoryId: 6 },
  { id: 48, name: 'اكسسوارات نسائية', categoryId: 6 },
  { id: 49, name: 'اكسسوارات رجالية', categoryId: 6 },
  { id: 50, name: 'محلات صيانة', categoryId: 7 },
  { id: 51, name: 'محلات غذائية', categoryId: 7 },
  { id: 52, name: 'مطاعم و كافيتريات', categoryId: 7 },
  { id: 53, name: 'محلات تجارية', categoryId: 7 },
  { id: 54, name: 'خدمات طبية', categoryId: 7 },
  { id: 55, name: 'خدمات استشارية', categoryId: 7 },
  { id: 56, name: 'خدمات عامة', categoryId: 7 },
  { id: 57, name: 'أماكن ترفيه', categoryId: 7 },
  { id: 58, name: 'هدايا و العاب', categoryId: 7 },
  { id: 59, name: 'حيوانات أليفة', categoryId: 8 },
  { id: 60, name: 'أبقار', categoryId: 8 },
  { id: 61, name: 'طيور', categoryId: 8 },
  { id: 62, name: 'أسماك', categoryId: 8 },
  { id: 63, name: 'غنم و ماعز', categoryId: 8 },
  { id: 64, name: 'خيول', categoryId: 8 },
  { id: 65, name: 'أدوات حيوانات', categoryId: 8 },
  { id: 66, name: 'وظائف بدوام كامل', categoryId: 9 },
  { id: 67, name: 'وظائف بدوام جزئي', categoryId: 9 },
  { id: 68, name: 'وظائف حرة', categoryId: 9 },
  { id: 69, name: 'وظائف موسمية', categoryId: 9 },
  { id: 70, name: 'وظائف عن بعد', categoryId: 9 },
  { id: 71, name: 'وظائف تدريبية', categoryId: 9 },
  { id: 72, name: 'وظائف إدارية', categoryId: 9 },
  { id: 73, name: 'وظائف تقنية', categoryId: 9 },
  { id: 74, name: 'وظائف تعليمية', categoryId: 9 },
  { id: 75, name: 'وظائف صحية', categoryId: 9 },
];

const provinces = [
  { id: 1, name: 'الحسكة' },
  { id: 2, name: 'الرقة' },
  { id: 3, name: 'حلب' },
  { id: 4, name: 'إدلب' },
  { id: 5, name: 'اللاذقية' },
  { id: 6, name: 'طرطوس' },
  { id: 7, name: 'دير الزور' },
  { id: 8, name: 'حماة' },
  { id: 9, name: 'حمص' },
  { id: 10, name: 'ريف دمشق' },
  { id: 11, name: 'دمشق' },
  { id: 12, name: 'السويداء' },
  { id: 13, name: 'درعا' },
  { id: 14, name: 'القنيطرة' },
];

const majorAreas = [
  { id: 1, name: 'الحسكة', ProvinceId: 1 },
  { id: 2, name: 'القامشلي', ProvinceId: 1 },
  { id: 3, name: 'رأس العين', ProvinceId: 1 },
  { id: 4, name: 'المالكية', ProvinceId: 1 },
  { id: 5, name: 'الرقة', ProvinceId: 2 },
  { id: 6, name: 'الثورة', ProvinceId: 2 },
  { id: 7, name: 'تل أبيض', ProvinceId: 2 },
  { id: 8, name: 'السحارة', ProvinceId: 3 },
  { id: 9, name: 'حلب', ProvinceId: 3 },
  { id: 10, name: 'عفرين', ProvinceId: 3 },
  { id: 11, name: 'اعزاز', ProvinceId: 3 },
  { id: 12, name: 'الباب', ProvinceId: 3 },
  { id: 13, name: 'منبج', ProvinceId: 3 },
  { id: 14, name: 'سراقب', ProvinceId: 4 },
  { id: 15, name: 'رام حمدان', ProvinceId: 4 },
  { id: 16, name: 'معرتمصرين', ProvinceId: 4 },
  { id: 17, name: 'كفر يحمول', ProvinceId: 4 },
  { id: 18, name: 'زردنا', ProvinceId: 4 },
  { id: 19, name: 'إدلب', ProvinceId: 4 },
  { id: 20, name: 'جسر الشغور', ProvinceId: 4 },
  { id: 21, name: 'أريحا', ProvinceId: 4 },
  { id: 22, name: 'معرة النعمان', ProvinceId: 4 },
  { id: 23, name: 'اللاذقية', ProvinceId: 5 },
  { id: 24, name: 'جبلة', ProvinceId: 5 },
  { id: 25, name: 'القرداحة', ProvinceId: 5 },
  { id: 26, name: 'الحفة', ProvinceId: 5 },
  { id: 27, name: 'طرطوس', ProvinceId: 6 },
  { id: 28, name: 'بانياس', ProvinceId: 6 },
  { id: 29, name: 'صافيتا', ProvinceId: 6 },
  { id: 30, name: 'الشيخ بدر', ProvinceId: 6 },
  { id: 31, name: 'دير الزور', ProvinceId: 7 },
  { id: 32, name: 'الميادين', ProvinceId: 7 },
  { id: 33, name: 'البوكمال', ProvinceId: 7 },
  { id: 34, name: 'حماة', ProvinceId: 8 },
  { id: 35, name: 'محردة', ProvinceId: 8 },
  { id: 36, name: 'مصياف', ProvinceId: 8 },
  { id: 37, name: 'السلمية', ProvinceId: 8 },
  { id: 38, name: 'حمص', ProvinceId: 9 },
  { id: 39, name: 'تدمر', ProvinceId: 9 },
  { id: 40, name: 'القصير', ProvinceId: 9 },
  { id: 41, name: 'الرستن', ProvinceId: 9 },
  { id: 42, name: 'دوما', ProvinceId: 10 },
  { id: 43, name: 'داريا', ProvinceId: 10 },
  { id: 44, name: 'القطيفة', ProvinceId: 10 },
  { id: 45, name: 'الزبداني', ProvinceId: 10 },
  { id: 46, name: 'يبرود', ProvinceId: 10 },
  { id: 47, name: 'دمشق', ProvinceId: 11 },
  { id: 48, name: 'المزة', ProvinceId: 11 },
  { id: 49, name: 'كفرسوسة', ProvinceId: 11 },
  { id: 50, name: 'المالكي', ProvinceId: 11 },
  { id: 51, name: 'السويداء', ProvinceId: 12 },
  { id: 52, name: 'شهبا', ProvinceId: 12 },
  { id: 53, name: 'صلخد', ProvinceId: 12 },
  { id: 54, name: 'درعا', ProvinceId: 13 },
  { id: 55, name: 'بصرى', ProvinceId: 13 },
  { id: 56, name: 'الحراك', ProvinceId: 13 },
  { id: 57, name: 'إزرع', ProvinceId: 13 },
  { id: 58, name: 'القنيطرة', ProvinceId: 14 },
];

module.exports = { currencies, categories, subCategories, provinces, majorAreas };