const currencies = [
    { id: 1, name: '$' },
    { id: 2, name: '€' },
    { id: 3, name: 'ل.س' },
    { id: 4, name: 'ل.ت' },
    { id: 5, name: 'حسب الحجم' },
    { id: 6, name: 'حسب الوزن' },
    { id: 7, name: 'حسب الكمية' }
];

// التصنيفات الرئيسية
const categories = [
  { id: 1, name: 'مركبات' },
  { id: 2, name: 'عقارات' },
  { id: 3, name: 'فرص عمل' },
  { id: 4, name: 'الكترونيات و كهربائيات' },
  { id: 5, name: 'أثاث' },
  { id: 6, name: 'ملابس' },
  { id: 7, name: 'المجتمع' },
  { id: 8, name: 'معدات صناعية' }
];

// التصنيفات الفرعية
const subCategories = [
  // مركبات
  { id: 1, name: 'سيارات سياحية', categoryId: 1 },
  { id: 2, name: 'سيارات كهربائية', categoryId: 1 },
  { id: 3, name: 'دفع رباعي', categoryId: 1 },
  { id: 4, name: 'بيك أب', categoryId: 1 },
  { id: 5, name: 'سيارات شحن', categoryId: 1 },
  { id: 6, name: 'دراجات نارية', categoryId: 1 },
  { id: 7, name: 'ميكرو أو فان أو باص', categoryId: 1 },
  { id: 8, name: 'اليات ثقيلة', categoryId: 1 },
  { id: 9, name: 'مركبات بحرية', categoryId: 1 },
  { id: 10, name: 'مركبات متضررة', categoryId: 1 },

  // عقارات
  { id: 11, name: 'شقة', categoryId: 2 },
  { id: 12, name: 'أراضي', categoryId: 2 },
  { id: 13, name: 'محلات', categoryId: 2 },
  { id: 14, name: 'مكان عمل جاهز', categoryId: 2 },
  { id: 15, name: 'بناء كامل', categoryId: 2 },
  { id: 16, name: 'فيلا', categoryId: 2 },
  { id: 17, name: 'مزارع', categoryId: 2 },

  // فرص عمل
  { id: 18, name: 'وظائف التخصصات الهندسية', categoryId: 3 },
  { id: 19, name: 'وظائف التخصصات الطبية', categoryId: 3 },
  { id: 20, name: 'وظائف قانونية و استشارية', categoryId: 3 },
  { id: 21, name: 'وظائف مطاعم', categoryId: 3 },
  { id: 22, name: 'وظائف تدريس', categoryId: 3 },
  { id: 23, name: 'وظائف سياحية', categoryId: 3 },
  { id: 24, name: 'وظائف فندقية', categoryId: 3 },
  { id: 25, name: 'وظائف عمال بناء و مصانع', categoryId: 3 },
  { id: 26, name: 'وظائف الرعاية الصحية', categoryId: 3 },
  { id: 27, name: 'وظائف الترجمة', categoryId: 3 },
  { id: 28, name: 'وظائف تكنولوجيا و برمجة و تصميم', categoryId: 3 },
  { id: 29, name: 'وظائف خدمة المنازل و المكاتب', categoryId: 3 },
  { id: 30, name: 'وظائف العقارات', categoryId: 3 },
  { id: 31, name: 'وظائف المحاسبة و المالية', categoryId: 3 },
  { id: 32, name: 'وظائف الاعمال المكتبية و السكرتارية', categoryId: 3 },
  { id: 33, name: 'وظائف المهن الصناعية و الحرف اليدوية', categoryId: 3 },
  { id: 34, name: 'وظائف الإعلام', categoryId: 3 },
  { id: 35, name: 'وظائف الشحن و النقل', categoryId: 3 },
  { id: 36, name: 'وظائف الغزل و النسيج', categoryId: 3 },
  { id: 37, name: 'وظائف أخرى', categoryId: 3 },

  // الكترونيات و كهربائيات
  { id: 38, name: 'هواتف', categoryId: 4 },
  { id: 39, name: 'كمبيوتر ثابت', categoryId: 4 },
  { id: 40, name: 'لابتوب', categoryId: 4 },
  { id: 41, name: 'طيارات درون', categoryId: 4 },
  { id: 42, name: 'شاشات', categoryId: 4 },
  { id: 43, name: 'ألواح طاقة شمسية', categoryId: 4 },
  { id: 44, name: 'أدوات منزلية كهربائية', categoryId: 4 },
  { id: 45, name: 'اكسسوارات', categoryId: 4 },
  { id: 46, name: 'هدايا و ألعاب', categoryId: 4 },

  // أثاث
  { id: 47, name: 'غرف نوم', categoryId: 5 },
  { id: 48, name: 'غرف جلوس', categoryId: 5 },
  { id: 49, name: 'غرف ضيوف', categoryId: 5 },
  { id: 50, name: 'أثاث مكتب', categoryId: 5 },
  { id: 51, name: 'كهربائيات منزل', categoryId: 5 },
  { id: 52, name: 'مستلزمات مطبخية', categoryId: 5 },
  { id: 53, name: 'اكسسوارات و صمديات', categoryId: 5 },
  { id: 54, name: 'أثاثات أخرى', categoryId: 5 },

  // ملابس
  { id: 55, name: 'ملابس رجالي', categoryId: 6 },
  { id: 56, name: 'ملابس نسائية', categoryId: 6 },
  { id: 57, name: 'ملابس ولادي صبيان', categoryId: 6 },
  { id: 58, name: 'ملابس ولادي بنات', categoryId: 6 },

  // المجتمع
  { id: 59, name: 'محلات صيانة أدوات كهربائية', categoryId: 7 },
  { id: 60, name: 'محلات تمديدات كهربائية و صحية', categoryId: 7 },
  { id: 61, name: 'محلات الدهانات و الديكور', categoryId: 7 },
  { id: 62, name: 'محلات صيانة الاكترونيات', categoryId: 7 },
  { id: 63, name: 'مطاعم و مقاهي و منتزهات', categoryId: 7 },
  { id: 64, name: 'محلات تجارية', categoryId: 7 },
  { id: 65, name: 'خدمات طبية', categoryId: 7 },
  { id: 66, name: 'خدمات استشارية و قانونية', categoryId: 7 },
  { id: 67, name: 'خدمات مالية', categoryId: 7 },
  { id: 68, name: 'أماكن ترفيه', categoryId: 7 },
  { id: 69, name: 'خدمات عامة', categoryId: 7 },
  { id: 70, name: 'هدايا و ألعاب', categoryId: 7 },
  { id: 71, name: 'مكاتب حوالات و صرافة', categoryId: 7 },

  // معدات صناعية
  { id: 71, name: 'تجهيزات مطاعم و أفران', categoryId: 8 },
  { id: 72, name: 'معامل بلاستيك و حديد', categoryId: 8 },
  { id: 73, name: 'معامل خياطة', categoryId: 8 },
  { id: 74, name: 'مولدات', categoryId: 8 },
  { id: 75, name: 'ديكورات محلات', categoryId: 8 },
  { id: 76, name: 'هنكارات', categoryId: 8 },
  { id: 77, name: 'معدات زراعية', categoryId: 8 },
  { id: 78, name: 'معدات أخرى', categoryId: 8 },
];


const provinces = [
  { id: 1, name: 'حلب' },
  { id: 2, name: 'دمشق' },
  { id: 3, name: 'إدلب' },
  { id: 4, name: 'حمص' },
  { id: 5, name: 'درعا' },
  { id: 6, name: 'الرقة' },
  { id: 7, name: 'دير الزور' },
  { id: 8, name: 'اللاذقية' },
  { id: 9, name: 'طرطوس' },
  { id: 10, name: 'حماة' },
  { id: 11, name: 'السويداء' },
  { id: 12, name: 'ريف دمشق' },
  { id: 13, name: 'الحسكة' },
  { id: 14, name: 'القنيطرة' },
];

const majorAreas = [
  // حلب
  { id: 1, name: 'حلب', ProvinceId: 1 },
  { id: 2, name: 'اعزاز', ProvinceId: 1 },
  { id: 3, name: 'عفرين', ProvinceId: 1 },
  { id: 4, name: 'الباب', ProvinceId: 1 },
  { id: 5, name: 'منبج', ProvinceId: 1 },
  { id: 6, name: 'السحارة', ProvinceId: 1 },
  { id: 7, name: 'تل رفعت', ProvinceId: 1 },
  { id: 8, name: 'جرابلس', ProvinceId: 1 },
  { id: 9, name: 'دير حافر', ProvinceId: 1 },
  { id: 10, name: 'الأتارب', ProvinceId: 1 },
  { id: 11, name: 'المسيفرة', ProvinceId: 1 },
  { id: 12, name: 'الراعي', ProvinceId: 1 },
  { id: 13, name: 'مارع', ProvinceId: 1 },
  { id: 14, name: 'نبل', ProvinceId: 1 },
  { id: 15, name: 'الزهراء', ProvinceId: 1 },

  // دمشق
  { id: 16, name: 'دمشق', ProvinceId: 2 },
  { id: 17, name: 'المزة', ProvinceId: 2 },
  { id: 18, name: 'كفرسوسة', ProvinceId: 2 },
  { id: 19, name: 'المالكي', ProvinceId: 2 },
  { id: 20, name: 'برزة', ProvinceId: 2 },
  { id: 21, name: 'القابون', ProvinceId: 2 },
  { id: 22, name: 'ركن الدين', ProvinceId: 2 },
  { id: 23, name: 'الميدان', ProvinceId: 2 },
  { id: 24, name: 'الشيخ محي الدين', ProvinceId: 2 },
  { id: 25, name: 'الصالحية', ProvinceId: 2 },
  { id: 26, name: 'باب توما', ProvinceId: 2 },
  { id: 27, name: 'باب شرقي', ProvinceId: 2 },
  { id: 28, name: 'الحميدية', ProvinceId: 2 },
  { id: 29, name: 'الشاغور', ProvinceId: 2 },
  { id: 30, name: 'الزاهرة', ProvinceId: 2 },

  // إدلب
  { id: 31, name: 'إدلب', ProvinceId: 3 },
  { id: 32, name: 'سراقب', ProvinceId: 3 },
  { id: 33, name: 'معرة النعمان', ProvinceId: 3 },
  { id: 34, name: 'جسر الشغور', ProvinceId: 3 },
  { id: 35, name: 'أريحا', ProvinceId: 3 },
  { id: 36, name: 'معرتمصرين', ProvinceId: 3 },
  { id: 37, name: 'كفر يحمول', ProvinceId: 3 },
  { id: 38, name: 'زردنا', ProvinceId: 3 },
  { id: 39, name: 'رام حمدان', ProvinceId: 3 }, // مضافة عشوائياً
  { id: 40, name: 'سرمين', ProvinceId: 3 },
  { id: 41, name: 'تفتناز', ProvinceId: 3 },
  { id: 42, name: 'بنش', ProvinceId: 3 },
  { id: 43, name: 'خان شيخون', ProvinceId: 3 },
  { id: 44, name: 'الدانا', ProvinceId: 3 },
  { id: 45, name: 'سلقين', ProvinceId: 3 },

  // حمص
  { id: 46, name: 'حمص', ProvinceId: 4 },
  { id: 47, name: 'تدمر', ProvinceId: 4 },
  { id: 48, name: 'القصير', ProvinceId: 4 },
  { id: 49, name: 'الرستن', ProvinceId: 4 },
  { id: 50, name: 'تلبيسة', ProvinceId: 4 },
  { id: 51, name: 'المخرم', ProvinceId: 4 },
  { id: 52, name: 'الحولة', ProvinceId: 4 },
  { id: 53, name: 'الدار الكبيرة', ProvinceId: 4 },
  { id: 54, name: 'تلدو', ProvinceId: 4 },
  { id: 55, name: 'الزعفرانة', ProvinceId: 4 },
  { id: 56, name: 'المشرفة', ProvinceId: 4 },
  { id: 57, name: 'الفرزل', ProvinceId: 4 },
  { id: 58, name: 'القصير الجديدة', ProvinceId: 4 },
  { id: 59, name: 'تل شنان', ProvinceId: 4 },
  { id: 60, name: 'تل عمري', ProvinceId: 4 },

  // درعا
  { id: 61, name: 'درعا', ProvinceId: 5 },
  { id: 62, name: 'بصرى', ProvinceId: 5 },
  { id: 63, name: 'الحراك', ProvinceId: 5 },
  { id: 64, name: 'إزرع', ProvinceId: 5 },
  { id: 65, name: 'نوى', ProvinceId: 5 },
  { id: 66, name: 'الصنمين', ProvinceId: 5 },
  { id: 67, name: 'الشيخ مسكين', ProvinceId: 5 },
  { id: 68, name: 'داعل', ProvinceId: 5 },
  { id: 69, name: 'الجيزة', ProvinceId: 5 },
  { id: 70, name: 'الطيبة', ProvinceId: 5 },
  { id: 71, name: 'المزيريب', ProvinceId: 5 },
  { id: 72, name: 'تسيل', ProvinceId: 5 },
  { id: 73, name: 'سحم الجولان', ProvinceId: 5 },
  { id: 74, name: 'غصم', ProvinceId: 5 },
  { id: 75, name: 'النعيمة', ProvinceId: 5 },

  // الرقة
  { id: 76, name: 'الرقة', ProvinceId: 6 },
  { id: 77, name: 'الثورة', ProvinceId: 6 },
  { id: 78, name: 'تل أبيض', ProvinceId: 6 },
  { id: 79, name: 'المنصورة', ProvinceId: 6 },
  { id: 80, name: 'معدان', ProvinceId: 6 },
  { id: 81, name: 'الكرامة', ProvinceId: 6 },
  { id: 82, name: 'السبخة', ProvinceId: 6 },
  { id: 83, name: 'الجرنية', ProvinceId: 6 },
  { id: 84, name: 'حزيمة', ProvinceId: 6 },
  { id: 85, name: 'السلحبية', ProvinceId: 6 },
  { id: 86, name: 'الحمام', ProvinceId: 6 },
  { id: 87, name: 'السويدية', ProvinceId: 6 },
  { id: 88, name: 'الطويحينة', ProvinceId: 6 },
  { id: 89, name: 'السبخة الجديدة', ProvinceId: 6 },
  { id: 90, name: 'الكرامة الجديدة', ProvinceId: 6 },

  // دير الزور
  { id: 91, name: 'دير الزور', ProvinceId: 7 },
  { id: 92, name: 'الميادين', ProvinceId: 7 },
  { id: 93, name: 'البوكمال', ProvinceId: 7 },
  { id: 94, name: 'موحسن', ProvinceId: 7 },
  { id: 95, name: 'العشارة', ProvinceId: 7 },
  { id: 96, name: 'القورية', ProvinceId: 7 },
  { id: 97, name: 'الكسرة', ProvinceId: 7 },
  { id: 98, name: 'الحسينية', ProvinceId: 7 },
  { id: 99, name: 'الصور', ProvinceId: 7 },
  { id: 100, name: 'الطابية', ProvinceId: 7 },
  { id: 101, name: 'الجنينة', ProvinceId: 7 },
  { id: 102, name: 'الهرى', ProvinceId: 7 },
  { id: 103, name: 'الصالحية', ProvinceId: 7 },
  { id: 104, name: 'العبد', ProvinceId: 7 },
  { id: 105, name: 'الحويقة', ProvinceId: 7 },

  // اللاذقية
  { id: 106, name: 'اللاذقية', ProvinceId: 8 },
  { id: 107, name: 'جبلة', ProvinceId: 8 },
  { id: 108, name: 'القرداحة', ProvinceId: 8 },
  { id: 109, name: 'الحفة', ProvinceId: 8 },
  { id: 110, name: 'رأس البسيط', ProvinceId: 8 },
  { id: 111, name: 'القسطل', ProvinceId: 8 },
  { id: 112, name: 'عين الشرقية', ProvinceId: 8 },
  { id: 113, name: 'الدالية', ProvinceId: 8 },
  { id: 114, name: 'صلنفة', ProvinceId: 8 },
  { id: 115, name: 'البهلولية', ProvinceId: 8 },
  { id: 116, name: 'عين العروس', ProvinceId: 8 },
  { id: 117, name: 'القطيلبية', ProvinceId: 8 },
  { id: 118, name: 'الرويمية', ProvinceId: 8 },
  { id: 119, name: 'الزوبار', ProvinceId: 8 },
  { id: 120, name: 'الكرامة', ProvinceId: 8 },

  // طرطوس
  { id: 121, name: 'طرطوس', ProvinceId: 9 },
  { id: 122, name: 'بانياس', ProvinceId: 9 },
  { id: 123, name: 'صافيتا', ProvinceId: 9 },
  { id: 124, name: 'الشيخ بدر', ProvinceId: 9 },
  { id: 125, name: 'الدريكيش', ProvinceId: 9 },
  { id: 126, name: 'حمام واصل', ProvinceId: 9 },
  { id: 127, name: 'القدموس', ProvinceId: 9 },
  { id: 128, name: 'الروضة', ProvinceId: 9 },
  { id: 129, name: 'الصفصافة', ProvinceId: 9 },
  { id: 130, name: 'الحميدية', ProvinceId: 9 },
  { id: 131, name: 'الدوير', ProvinceId: 9 },
  { id: 132, name: 'المنطار', ProvinceId: 9 },
  { id: 133, name: 'الشيخ سعد', ProvinceId: 9 },
  { id: 134, name: 'الزرقات', ProvinceId: 9 },
  { id: 135, name: 'الحميدية الجديدة', ProvinceId: 9 },

  // حماة
  { id: 136, name: 'حماة', ProvinceId: 10 },
  { id: 137, name: 'محردة', ProvinceId: 10 },
  { id: 138, name: 'مصياف', ProvinceId: 10 },
  { id: 139, name: 'السلمية', ProvinceId: 10 },
  { id: 140, name: 'صوران', ProvinceId: 10 },
  { id: 141, name: 'طيبة الإمام', ProvinceId: 10 },
  { id: 142, name: 'كفرزيتا', ProvinceId: 10 },
  { id: 143, name: 'اللطامنة', ProvinceId: 10 },
  { id: 144, name: 'حلفايا', ProvinceId: 10 },
  { id: 145, name: 'الحمرا', ProvinceId: 10 },
  { id: 146, name: 'الشيحة', ProvinceId: 10 },
  { id: 147, name: 'الربيعة', ProvinceId: 10 },
  { id: 148, name: 'الحميدية', ProvinceId: 10 },
  { id: 149, name: 'الحميدية الجديدة', ProvinceId: 10 },
  { id: 150, name: 'الحميدية القديمة', ProvinceId: 10 },

  // السويداء
  { id: 151, name: 'السويداء', ProvinceId: 11 },
  { id: 152, name: 'شهبا', ProvinceId: 11 },
  { id: 153, name: 'صلخد', ProvinceId: 11 },
  { id: 154, name: 'القريا', ProvinceId: 11 },
  { id: 155, name: 'المزرعة', ProvinceId: 11 },
  { id: 156, name: 'الثعلة', ProvinceId: 11 },
  { id: 157, name: 'عريقة', ProvinceId: 11 },
  { id: 158, name: 'سليم', ProvinceId: 11 },
  { id: 159, name: 'مفعلة', ProvinceId: 11 },
  { id: 160, name: 'الكفر', ProvinceId: 11 },
  { id: 161, name: 'حبران', ProvinceId: 11 },
  { id: 162, name: 'العفينة', ProvinceId: 11 },
  { id: 163, name: 'الهويا', ProvinceId: 11 },
  { id: 164, name: 'الهيات', ProvinceId: 11 },
  { id: 165, name: 'السويداء الجديدة', ProvinceId: 11 },

  // ريف دمشق
  { id: 166, name: 'دوما', ProvinceId: 12 },
  { id: 167, name: 'داريا', ProvinceId: 12 },
  { id: 168, name: 'القطيفة', ProvinceId: 12 },
  { id: 169, name: 'الزبداني', ProvinceId: 12 },
  { id: 170, name: 'يبرود', ProvinceId: 12 },
  { id: 171, name: 'التل', ProvinceId: 12 },
  { id: 172, name: 'حرستا', ProvinceId: 12 },
  { id: 173, name: 'سقبا', ProvinceId: 12 },
  { id: 174, name: 'حمورية', ProvinceId: 12 },
  { id: 175, name: 'كفربطنا', ProvinceId: 12 },
  { id: 176, name: 'عين ترما', ProvinceId: 12 },
  { id: 177, name: 'مضايا', ProvinceId: 12 },
  { id: 178, name: 'الكسوة', ProvinceId: 12 },
  { id: 179, name: 'النبك', ProvinceId: 12 },
  { id: 180, name: 'الزبداني الجديدة', ProvinceId: 12 },

  // الحسكة
  { id: 181, name: 'الحسكة', ProvinceId: 13 },
  { id: 182, name: 'القامشلي', ProvinceId: 13 },
  { id: 183, name: 'رأس العين', ProvinceId: 13 },
  { id: 184, name: 'المالكية', ProvinceId: 13 },
  { id: 185, name: 'تل تمر', ProvinceId: 13 },
  { id: 186, name: 'عامودا', ProvinceId: 13 },
  { id: 187, name: 'الدرباسية', ProvinceId: 13 },
  { id: 188, name: 'اليعربية', ProvinceId: 13 },
  { id: 189, name: 'تل براك', ProvinceId: 13 },
  { id: 190, name: 'تل حميس', ProvinceId: 13 },
  { id: 191, name: 'تل كوجر', ProvinceId: 13 },
  { id: 192, name: 'الهول', ProvinceId: 13 },
  { id: 193, name: 'القحطانية', ProvinceId: 13 },
  { id: 194, name: 'تل علو', ProvinceId: 13 },
  { id: 195, name: 'الحسكة الجديدة', ProvinceId: 13 },

  // القنيطرة
  { id: 196, name: 'القنيطرة', ProvinceId: 14 },
  { id: 197, name: 'خان أرنبة', ProvinceId: 14 },
  { id: 198, name: 'جباتا الزيت', ProvinceId: 14 },
  { id: 199, name: 'الرفيد', ProvinceId: 14 },
  { id: 200, name: 'عين التينة', ProvinceId: 14 },
  { id: 201, name: 'مجدل شمس', ProvinceId: 14 },
  { id: 202, name: 'أم باطنة', ProvinceId: 14 },
  { id: 203, name: 'القصيبة', ProvinceId: 14 },
  { id: 204, name: 'الصمدانية', ProvinceId: 14 },
  { id: 205, name: 'الحميدية', ProvinceId: 14 },
  { id: 206, name: 'المنصورة', ProvinceId: 14 },
  { id: 207, name: 'السويسة', ProvinceId: 14 },
  { id: 208, name: 'الحميدية الجديدة', ProvinceId: 14 },
  { id: 209, name: 'الحميدية القديمة', ProvinceId: 14 },
  { id: 210, name: 'القنيطرة الجديدة', ProvinceId: 14 },
  
  { id: 211, name: 'عين شيب ', ProvinceId: 3 },
  { id: 212, name: 'سرمدا', ProvinceId: 3 },
  { id: 213, name: 'حزانو', ProvinceId: 3 }
];

module.exports = { currencies, categories, subCategories, provinces, majorAreas };